name: Linting

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            styling_requirements.txt
            src/requirements.txt
            tests/tests_requirements.txt
      - name: Install dependencies
        run: |
          pip install -Ur styling_requirements.txt
          pip install -Ur src/requirements.txt
          pip install -Ur tests/tests_requirements.txt
      - name: PyLint
        run: |
          pylint src/ tests/
