name: Linting

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v7
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            cole/requirements.txt
            tests/tests_requirements.txt
      - name: Install dependencies
        run: |
          pip install pylint
          pip install -Ur cole/requirements.txt
          pip install -Ur tests/tests_requirements.txt
      - name: PyLint
        run: |
          pylint cole/ tests/
