name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            src/requirements.txt
            tests/tests_requirements.txt
      - name: Install dependencies
        run: |
          pip install -Ur src/requirements.txt
          pip install -Ur tests/tests_requirements.txt
      - name: Test with pytest
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pytest
